Connect/Models/ApplyTimingViewModel.cs
using Connect.Classes.DataModels;
using System.Collections.Generic;

namespace Connect.Models
{
    public class ApplyTimingViewModel
    {
        public List<BatchTiming> AvailableTimings { get; set; }
        public int SelectedBatchTimingId { get; set; }
    }
}

Connect/Models/ApplyViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Connect.Models
{
	public class ApplyViewModel
	{
		[Required]
		[MaxLength(50)]
		[RegularExpression(@"^[a-zA-Z0-9 ]*$", ErrorMessage = "Only alphabets and numbers are allowed")]
		public string Name { get; set; }
		[Required]
		[MaxLength(50)]
		[DataType(DataType.EmailAddress, ErrorMessage = "Enter in the format e.g username@gmail.com")]
		[Remote("DoesEmailExist", "Validation", HttpMethod = "GET", ErrorMessage = "Email Already Exists")]
		public string Email { get; set; }
		[Required]
		[RegularExpression(@"^[0-9]*$", ErrorMessage = "Only numbers are allowed with a maximum of 14 digits.")]
		public long? Phone { get; set; }
		[Required]
		[RegularExpression(@"^(1[2-9]|[2-6][0-9]|99)$", ErrorMessage = "Your age must range between 12 and 99.")]
		public int? Age { get; set; }

		[Required]
		[DataType(DataType.Password, ErrorMessage = "between 6 and 12 characters are allowed")]
		public string Password { get; set; }

		[Required]
		[DataType(DataType.Password, ErrorMessage = "between 6 and 12 characters are allowed")]
		public string ConfirmPassword { get; set; }

		public string PaymentMethod { get; set; }

		[RegularExpression(@"^[0-9]{10}$", ErrorMessage = "Please enter a 10 digit number")]
		public long? PaymentCodeEasyPaisa { get; set; }

		[RegularExpression(@"^\d{4}$", ErrorMessage = "Please enter the numbers in the format [1234 - 5678]")]
		public int? PaymentCodeManualPreHyphen { get; set; }
		public int? PaymentCodeManualPostHyphen { get; set; }

		//public List<InterviewSlot> AvailableInterviewSlots { get; set; }
        //public List<BatchTiming> AvailableBatchTimings { get; set; }
        public int SelectedInterviewSlotId { get; set; }
        public int SelectedBatchTimingId { get; set; }

        //public bool PaidThroughJazz { get; set; }
        //public bool PaidCashAtInstitute { get; set; }
        //public bool PaidThroughOnlineBank { get; set; }
        //public string PaymentMethod { get; set; }
        //public string PaymentCodeJazz { get; set; }
        //public string PaymentCodeOnlineBank { get; set; }
        //[RegularExpression(@"^[0-9]*$", ErrorMessage = "Only numbers are allowed with a maximum of 13 digits.")]
        //public string PaymentCodeManual { get; set; }
        public string Message { get; set; } = "";
        //[RegularExpression(@"^[a-zA-Z0-9]*$", ErrorMessage = "Only alphabets and numbers are allowed. No spaces are allowed")]
        //public string FatherName { get; set; }
        //[Required]
        //[RegularExpression(@"^[a-zA-Z0-9]*$", ErrorMessage = "Only alphabets and numbers are allowed. No spaces are allowed")]
        //public string LastName { get; set; }

        //public ApplyingFor ApplyingFor { get; set; }
        //public CurrentSection CurrentSection { get; set; }
        public CurrentStatus CurrentStatus { get; set; }
        public Campus Campus { get; set; }
    }

    public class ApplyAdminViewModel
    {
        [Required]
        [MaxLength(50)]
        [RegularExpression(@"^[a-zA-Z0-9 ]*$", ErrorMessage = "Only alphabets and numbers are allowed")]
        public string Name { get; set; }
        [Required]
        [MaxLength(50)]
        [DataType(DataType.EmailAddress, ErrorMessage = "Enter in the format e.g username@gmail.com")]
        [Remote("DoesEmailExist", "Validation", HttpMethod = "GET", ErrorMessage = "Email Already Exists")]
        public string Email { get; set; }
        [Required]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Only numbers are allowed with a maximum of 14 digits.")]
        public long? Phone { get; set; }
        [Required]
        [RegularExpression(@"^(1[2-9]|[2-6][0-9]|99)$", ErrorMessage = "Your age must range between 12 and 99.")]
        public int? Age { get; set; }

        [Required]
        [DataType(DataType.Password, ErrorMessage = "between 6 and 12 characters are allowed")]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password, ErrorMessage = "between 6 and 12 characters are allowed")]
        public string ConfirmPassword { get; set; }

        public string PaymentMethod { get; set; }

        [RegularExpression(@"^[0-9]{10}$", ErrorMessage = "Please enter a 10 digit number")]
        public long? PaymentCodeEasyPaisa { get; set; }

        //[RegularExpression(@"^\d{4}$", ErrorMessage = "Please enter the numbers in the format [1234 - 5678]")]
        //public int? PaymentCodeManualPreHyphen { get; set; }
        //public int? PaymentCodeManualPostHyphen { get; set; }

        //public int SelectedBatchTimingId { get; set; }

        public string Message { get; set; } = "";
        public CurrentStatus CurrentStatus { get; set; }
        public Campus Campus { get; set; }
        public int SelectedBatchTimingId { get; set; }
    }
}

Connect/Controllers/ApplyController.cs
using System;
using System.Configuration;
using System.Threading;
using System.Web.Mvc;
using Connect.Classes;
using Connect.Classes.Dapper;
using Connect.Classes.DataModels;
using Connect.Classes.Helpers;
using Connect.Classes.Security;
using Connect.Models;

namespace Connect.Controllers
{
    public class ApplyController : Controller
    {
	    // GET: Apply
	    [HttpGet]
	    [Route("apply")]
	    public ActionResult Apply(Guid? id = null, string method = null)
	    {
		    if (id == null || id == Guid.Empty) 
		    {
			    if (method != "internal")
			    {
				    var deadlineOn = DeadlineHelper.IsDeadlineOn();
				    if (deadlineOn)
					    return RedirectToAction("ApplyLocked", "Confirmation");
			    }
                else
                {
                    TempData["method"] = "internal";
                }
		    }

		    SessionHelper.Signout();
		    if (id != null && id != Guid.Empty)
		    {
				var isRegistered = new IndividualRepository().IsAccountVerified(id.Value.ToString());

			    // TODO: if the code is wrong or this person is blacklisted, then send to the unverified page. 
				if (isRegistered)
					return RedirectToAction("authenticate", "Login");
		    }

			var model = new ApplyViewModel();
			//model.AvailableInterviewSlots = new InterviewRepository().GetAvailableInterviewSlots();
			return View(model);
		}

        [HttpPost]
	    [Route("apply")]
	    public ActionResult Apply(ApplyViewModel applyViewModel)
	    {
            var method = TempData["method"];
            TempData["method"] = "";

            var respository = new IndividualRepository();
		    var id = Guid.NewGuid();
            var currentBatch = ConfigurationManager.AppSettings["CurrentBatch"];
            var individual = new Individual
            {
                Id = id,
                Name = applyViewModel.Name,
                Email = applyViewModel.Email,
                Password = applyViewModel.Password,
                Phone = applyViewModel.Phone,
                Age = applyViewModel.Age,
                UserType = UserType.Applicant,
                RegistrationStatus = RegistrationStatus.UnRegistered,
                PaymentMethod = applyViewModel.PaymentMethod,
                PaymentCode = ValidateAndGetPaymentCode(applyViewModel.PaymentMethod, applyViewModel.PaymentCodeManualPreHyphen, applyViewModel.PaymentCodeManualPostHyphen, applyViewModel.PaymentCodeEasyPaisa, applyViewModel.Email),
                PaymentStatus = PaymentStatus.UnVerified,
                CurrentStatus = applyViewModel.CurrentStatus,
                Batch = GetBatchFromCampus(applyViewModel.Campus.ToString()),
                Campus = applyViewModel.Campus == Campus.NONE ? Campus.KHI : applyViewModel.Campus
            };
			
            // TODO: Complete this
		    individual.InterviewSlotId = applyViewModel.SelectedInterviewSlotId;
            individual.BatchTimingId = applyViewModel.SelectedBatchTimingId;

            // This should be checked
            //if (individual.PaymentMethod == "InterviewDay")
            // individual.InterviewSlotId = 1033;      // None
            //else
            // applyViewModel.Message = CheckIfPaymentCodeExist(individual.PaymentCode);

            if (!ModelState.IsValid)
		    {
				//applyViewModel.AvailableInterviewSlots = new InterviewRepository().GetAvailableInterviewSlots();
				return View(applyViewModel);
		    }

            individual.Batch = GetBatchFromCampus(individual.Campus.ToString());
                       
            if(method != null && method.ToString() == "internal")
            {
                individual.RegistrationStatus = RegistrationStatus.Registered;
                respository.CreateOrUpdateBasicIndividual(individual);
                return RedirectToAction("Submitted", "Confirmation", new { applyViewModel.Name });
            }

            respository.CreateOrUpdateBasicIndividual(individual);
		    SendEmail(applyViewModel.Email, individual.Id.ToString());
		    return RedirectToAction("Submitted", "Confirmation", new { applyViewModel.Name });
	    }

        [HttpGet]
        [AuthorizeRole(UserType.Ceo)]
        [Route("applyadmin")]
        public ActionResult ApplyAdmin()
        {
            var model = new ApplyAdminViewModel();

            return View(model);
        }

        [HttpPost]
        [Route("applyadmin")]
        public ActionResult ApplyAdmin(ApplyAdminViewModel applyViewModel)
        {
            var method = TempData["method"];
            TempData["method"] = "";

            var respository = new IndividualRepository();
            var id = Guid.NewGuid();
            var individual = new Individual
            {
                Id = id,
                Name = applyViewModel.Name,
                Email = applyViewModel.Email,
                Password = applyViewModel.Password,
                Phone = applyViewModel.Phone,
                Age = applyViewModel.Age,
                UserType = UserType.Applicant,
                RegistrationStatus = RegistrationStatus.Registered,
                PaymentStatus = PaymentStatus.Verified,
                CurrentStatus = applyViewModel.CurrentStatus,
                Batch = GetBatchFromCampus(applyViewModel.Campus.ToString()),
                Campus = applyViewModel.Campus
            };

            individual.BatchTimingId = applyViewModel.SelectedBatchTimingId;
            individual.InterviewSlotId = 0;

            if (!ModelState.IsValid)
            {
                return View(applyViewModel);
            }

            individual.Batch = GetBatchFromCampus(applyViewModel.Campus.ToString());

            respository.CreateOrUpdateBasicIndividual(individual);
            return RedirectToAction("GetIntervieweesForCeo", "Interview", new { applyViewModel.Name });
        }

        private string GetBatchFromCampus(string campus)
        {
            return ConfigurationManager.AppSettings["CourseCodeDatePart"] + campus;
        }

        private string ValidateAndGetPaymentCode(string paymentMethod, int? paymentCodeManualPreHyphen, int? paymentCodeManualPostHyphen, long? paymentCodeEasyPaisa, string email)
	    {
		    string paymentCode = string.Empty;

		    if (paymentMethod == "AlBurhan")
		    {
			    if (paymentCodeManualPreHyphen.HasValue && paymentCodeManualPreHyphen.Value > 0 && paymentCodeManualPostHyphen.HasValue && paymentCodeManualPostHyphen.Value > 0)
				    paymentCode = paymentCodeManualPreHyphen + "-" + paymentCodeManualPostHyphen;
			    else
				    ModelState.AddModelError("PaymentRequired", "You have opted to make a payment at Al Burhan. Once you have paid, enter your receipt number");
		    }

		    if (paymentMethod == "EasyPaisa")
		    {
			    if (paymentCodeEasyPaisa.HasValue && paymentCodeEasyPaisa.Value > 0)
				    paymentCode = paymentCodeEasyPaisa.ToString();
			    else
				    ModelState.AddModelError("PaymentRequired", "You have opted to pay through Easy Paisa. Once you have paid, enter your transaction id");
		    }

			return paymentCode;
	    }

	    private string CheckIfPaymentCodeExist(string paymentCode)
	    {
		    var errorMessage = "";
		    var isDuplicate = new IndividualRepository().DoesPaymentCodeExist(paymentCode);
		    if (isDuplicate)
		    {
			    errorMessage = "This payment code has already been used by another applicant.";
				ModelState.AddModelError("DuplicatePaymentCode", errorMessage);
		    }
		    return errorMessage;
	    }

		private static void SendEmail(string email, string id)
	    {
		    var subjectPending = "Thank you for applying.";
		    var siteAddress = ConfigurationManager.AppSettings["SiteAddress"];
		    var urlForNotVerified = siteAddress + $"/apply?id={id}";

		    string bodyPending;
			bodyPending =
				$"Your application has been received. Please click the link {urlForNotVerified} to activate your account. Once logged in, you will be required to complete your application";

			new Thread(delegate () {
				EmailHelper.SendEmail(email, subjectPending, bodyPending, ConfigurationManager.AppSettings["ActivationEmailCC"]);
			}).Start();
		}
    }
}

Connect/Controllers/ApplyTimingsController.cs
using Connect.Classes.Dapper;
using Connect.Classes.DataModels;
using Connect.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Web.Mvc;

namespace Connect.Controllers
{
    public class ApplyTimingsController : Controller
    {
        [HttpGet]
        [Route("AvailableBatchTimings")]
        public ActionResult AvailableBatchTimings(int campusSelection)
        {
            var model = new ApplyTimingViewModel();
            model.AvailableTimings = new List<BatchTiming>();
            List<BatchTiming> batchTimings = null;

            if (campusSelection != 0)
            {
                var campus = (Campus)campusSelection;
                if (campus != Campus.NONE)
                {
                    var batch = GetBatchFromCampus(campus.ToString());
                    batchTimings = new InterviewRepository().GetAvailableBatchTimings(batch);
                }
            }

            if (batchTimings != null)
            {
                model.AvailableTimings = batchTimings;
            }

            return PartialView("~/Views/Apply/ApplyTimings.cshtml", model);
        }

        [HttpGet]
        [Route("AvailableBatchTimingsByBatch")]
        public ActionResult AvailableBatchTimingsByBatch(string batch, Guid id)
        {
            var model = new ApplyTimingViewModel();
            model.AvailableTimings = new List<BatchTiming>();
            List<BatchTiming> batchTimings = null;

            var repo = new InterviewRepository();
            batchTimings = repo.GetAvailableBatchTimings(batch);
            model.SelectedBatchTimingId = repo.GetSelectedBatchTimingId(id);

            if (batchTimings != null)
            {
                model.AvailableTimings = batchTimings;
            }

            return PartialView("~/Views/Apply/ApplyTimings.cshtml", model);
        }

        private string GetBatchFromCampus(string campus)
        {
            return ConfigurationManager.AppSettings["CourseCodeDatePart"] + campus;
        }
    }
}

Connect/Views/Apply/ApplyAdmin.cshtml
﻿﻿@model Connect.Models.ApplyAdminViewModel
@{
    ViewBag.Title = "Apply Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Admin Application page (late applications)</h1>
    @using (Html.BeginForm())
    {
        <input type="hidden" value="true" id="hdnAdmin" />

        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="section-focus">
                <div>
                    <table id="details_plain_small">
                        <tr>
                            <td colspan="3">
                                <p class="section-heading2-sub"><span style="padding-left: 5pt;">Initial Details</span></p>
                            </td>
                        </tr>

                        <tr class="form-group">
                            <td>@Html.Label("Please select your current status", new { @class = "label-simple-small" })</td>
                            <td>
                                <div>
                                    @Html.EnumDropDownListFor(model => model.CurrentStatus, new { @class = "form-dropdown-my" })
                                </div>
                            </td>
                        </tr>

                        <tr class="form-group">
                            <td>
                                @Html.Label("Campus", new { @class = "label-simple-small" })
                            </td>
                            <td>
                                <div>
                                    @Html.EnumDropDownListFor(model => model.Campus, new { @class = "form-dropdown-my JS_Campus_Selection" })
                                </div>
                            </td>
                        </tr>

                        <tr class="form-group">
                            <td>@Html.LabelFor(model => model.Name, "Name", new { @class = "label-simple-small" })</td>
                            <td>
                                <div>
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "textbox-my", MaxLength = "50", MinLength = "1", placeholder = "Name" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </td>
                        </tr>

                        <tr class="form-group">
                            <td>@Html.LabelFor(model => model.Email, "Email", new { @class = "label-simple-small" })</td>
                            <td>
                                <div>
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "textbox-my", MaxLength = "80", MinLength = "6", placeholder = "Email: Username@gmail.com" } })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                </div>
                            </td>
                        </tr>

                        <tr class="form-group">
                            <td>@Html.LabelFor(model => model.Phone, "Phone", new { @class = "label-simple-small" })</td>
                            <td>
                                <div>
                                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "textbox-my JS_PhoneMaxLength", MaxLength = "14", MinLength = "5", placeholder = "Phone: 03xxxxxxxxx" } })
                                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                                </div>
                            </td>
                        </tr>

                        <tr class="form-group">
                            <td>@Html.LabelFor(model => model.Age, "Age", new { @class = "label-simple-small" })</td>
                            <td>
                                <div>
                                    @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "textbox-my JS_AgeRange", placeholder = "Age (in years eg. 35)" } })
                                    @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                                </div>
                            </td>
                        </tr>

                        <tr class="form-group">
                            <td>@Html.LabelFor(model => model.Password, "Password", new { @class = "label-simple-small" })</td>
                            <td>
                                <div>
                                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "textbox-my JS_Password", MinLength = "6", MaxLength = "12", placeholder = "Password (between 6 and 12 characters)" } })
                                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                </div>
                            </td>
                        </tr>

                        <tr class="form-group">
                            <td>@Html.LabelFor(model => model.ConfirmPassword, "Confirm Password", new { @class = "label-simple-small" })</td>
                            <td>
                                <div>
                                    @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "textbox-my JS_ConfirmPassword", MinLength = "6", MaxLength = "12", placeholder = "Confirm Password" } })
                                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                                </div>
                            </td>
                        </tr>

                    </table>
                </div>
                <p style="display: none; color: red;" class="JS_PasswordMisMatch">Your passwords do not match. Please re-enter.</p>
            </div>

            <div class="section-focus JS_TimingSelectionShowHide">
                @{ Html.RenderAction("AvailableBatchTimings", "ApplyTimings", new { campusSelection = 0 }); }
            </div>
            <div>
                <div>
                    <input type="submit" value="Apply" class="btn btn-default button-my-apply submit_apply_admin" />
                </div>
            </div>
        </div>
    }


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Connect/Views/Apply/ApplyTimings.cshtml
@model Connect.Models.ApplyTimingViewModel

@if (Model.AvailableTimings != null)
{
    <div>
        <table id="details_plain_small">
            <tr>
                <td colspan="3">
                    <hr style="height: 0.5px; background-color: lightgray;" />
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <p class="section-heading2-sub"><span style="padding-left: 15px;">Timings</span></p>
                </td>
            </tr>

            <tr class="form-group">
                <td>@Html.Label("Please select your class timing for the course", new { @class = "label-simple-small" })</td>
                <td>
                    <div>
                        @Html.DropDownListFor(x => x.SelectedBatchTimingId, new SelectList(Model.AvailableTimings, "BatchTimingId", "Timing"), new { @class = "form-dropdown-my" })
                    </div>
                </td>
            </tr>
        </table>
    </div>
}