Connect/Controllers/SignupController.cs
using System;
using System.Web.Mvc;
using Connect.Classes;
using Connect.Classes.Dapper;
using Connect.Classes.DataModels;
using Connect.Classes.Helpers;
using Connect.Classes.Security;
using Connect.Models;

namespace Connect.Controllers
{
	[AuthorizeRole(UserType.Applicant, UserType.Panel, UserType.Ceo, UserType.PaymentAdministrator, UserType.Manager)]
    public class SignupController : Controller
    {
		[HttpGet]
	    [Route("register")]
	    public ActionResult Register(Guid? id)
		{
			Guid idInContext;

			if (id.HasValue)
			{
				if (SessionHelper.LoggedInUser.UserType == UserType.Applicant && SessionHelper.LoggedInUser.Id != id.Value)
				{
					return RedirectToAction("Authenticate", "Login");
				}

				idInContext = id.Value;
			}
			else
			{
				idInContext = SessionHelper.LoggedInUser.Id;
			}

			var model = new SignupViewModel();
			var repository = new InterviewRepository();

			var individualFromDb = new IndividualRepository().GetIndividualDetailsById(idInContext);

			// All the data needs to be filled into the model
			FillModelData(model, individualFromDb);

			model.AvailableInterviewSlots = new InterviewRepository().GetAvailableInterviewSlots(SessionHelper.LoggedInUser.Batch);
			model.SelectedInterviewSlotId = repository.GetSelectedInterviewSlot(idInContext);

            model.AvailableTimings = new InterviewRepository().GetAvailableBatchTimings(SessionHelper.LoggedInUser.Batch);
            model.SelectedBatchTimingId = repository.GetSelectedBatchTimingId(idInContext);

            if (SessionHelper.LoggedInUser.Batch.Contains("-BW") || SessionHelper.LoggedInUser.Batch.Contains("ISBW"))
            {
                return View("RegisterSisters", model);
            }
            else
            {
                return View(model);
            }
        }

		[HttpPost]
		[Route("register")]
		public ActionResult Register(SignupViewModel signupViewModel)
		{
			var respository = new IndividualRepository();
			var id = signupViewModel.Id;
			var individualFromDb = respository.GetIndividualDetailsById(id);
			FillFromModel(signupViewModel, individualFromDb);
			respository.UpdateIndividualDetails(individualFromDb);

			return RedirectToAction("PreviewForAdmin", "Main", new {id});
		}

		#region Private Methods

		private void FillFromModel(SignupViewModel model, Individual individualFromDb)
	    {
            if(model.NicNumber != null)
		        individualFromDb.NicNumber = model.NicNumber;

            if (model.OtherContact != null)
                individualFromDb.OtherContact = model.OtherContact;

                individualFromDb.MaritalStatus = model.MaritalStatus;

                individualFromDb.ResidentialAddress = model.ResidentialAddress;

                individualFromDb.PermanentAddress = model.PermanentAddress;

                individualFromDb.MatricGpa = model.MatricGpa;
                individualFromDb.MatricSubjects = model.MatricSubjects;
                individualFromDb.MatricInstitute = model.MatricInstitution;
                individualFromDb.IntermediateGpa = model.IntermediateGpa;
                individualFromDb.IntermediateSubjects = model.IntermediateSubjects;
                individualFromDb.IntermediateInstitute = model.IntermediateInstitution;
                individualFromDb.GraduationGpa = model.GraduationGpa;
                individualFromDb.GraduationSubjects = model.GraduationSubjects;
                individualFromDb.GraduationInstitute = model.GraduationInstitution;
                individualFromDb.MastersGpa = model.MastersGpa;
                individualFromDb.MastersSubjects = model.MastersSubjects;
                individualFromDb.MastersInstitution = model.MastersInstitution;
                individualFromDb.MsGpa = model.MsGpa;
                individualFromDb.MsSubjects = model.MsSubjects;
                individualFromDb.MsInstitution = model.MsInstitution;
                individualFromDb.PhdSubjects = model.PhdSubjects;
                individualFromDb.PhdInstitution = model.PhdInstitution;
                individualFromDb.OtherQualification = model.OtherQualification;

                individualFromDb.CurrentJob = model.CurrentJob;
                individualFromDb.CompanyName = model.CompanyName;
                individualFromDb.Designation = model.Designation;
                individualFromDb.TotalJobExperience = model.TotalJobExperience;

                individualFromDb.BusinessName = model.BusinessName;
                individualFromDb.BusinessArea = model.BusinessArea;
                individualFromDb.BusinessNature = model.BusinessNature;

                individualFromDb.AppliedBefore = model.AppliedBefore;

                individualFromDb.AnyReligiousEducation = model.AnyReligiousEducation;

                individualFromDb.ReligiousEducationSpecify = model.ReligiousEducationSpecify;
                individualFromDb.AnyOtherExpertise = model.AnyOtherExpertise;

                individualFromDb.CurrentStatus = model.CurrentStatus;

                individualFromDb.Education = model.Education;

            if(individualFromDb.RegistrationStatus == RegistrationStatus.UnRegistered || individualFromDb.RegistrationStatus == RegistrationStatus.Registered)
			    individualFromDb.RegistrationStatus = RegistrationStatus.Completed;

            //individualFromDb.Name = model.Name;
            if (model.Phone != null)
                individualFromDb.Phone = model.Phone;

            // new fields for sisters
            if (model.FatherOrHusbandName != null)
                individualFromDb.FatherOrHusbandName = model.FatherOrHusbandName;
            if (model.ClassSelection != null)
                individualFromDb.ClassSelection = model.ClassSelection;
            if (model.WhatsAppNumber != null)
                individualFromDb.WhatsAppNumber = model.WhatsAppNumber;
            if (model.EducationDetails != null)
                individualFromDb.EducationDetails = model.EducationDetails;
            if (model.Responsibilities != null)
                individualFromDb.Responsibilities = model.Responsibilities;
            if (model.ProfessionStudyBusinessDetails != null)
                individualFromDb.ProfessionStudyBusinessDetails = model.ProfessionStudyBusinessDetails;
            if (model.CityDetails != null)
                individualFromDb.CityDetails = model.CityDetails;

            if (model.SelectedBatchTimingId != 0)
                individualFromDb.BatchTimingId = model.SelectedBatchTimingId;

            if (!(SessionHelper.LoggedInUser.UserType == UserType.Applicant && individualFromDb.PaymentMethod == "InterviewDay" ))
				individualFromDb.InterviewSlotId = model.SelectedInterviewSlotId;
		}

		private void FillModelData(SignupViewModel model, Individual individual)
		{
			model.UserType = individual.UserType;
			model.Id = individual.Id;
			model.Name = individual.Name;
			model.Age = individual.Age;
			model.Email = individual.Email;
			model.Phone = individual.Phone;
			model.IndividualId = individual.IndividualId.ToString();
			model.NicNumber = individual.NicNumber;
			model.OtherContact = individual.OtherContact;
			model.MaritalStatus = individual.MaritalStatus;
			model.ResidentialAddress = individual.ResidentialAddress;
			model.PermanentAddress = individual.PermanentAddress;
			model.MatricGpa = individual.MatricGpa;
			model.MatricSubjects = individual.MatricSubjects;
			model.MatricInstitution = individual.MatricInstitute;
			model.IntermediateGpa = individual.IntermediateGpa;
			model.IntermediateSubjects = individual.IntermediateSubjects;
			model.IntermediateInstitution = individual.IntermediateInstitute;
			model.GraduationGpa = individual.GraduationGpa;
			model.GraduationSubjects = individual.GraduationSubjects;
			model.GraduationInstitution = individual.GraduationInstitute;
			model.MastersGpa = individual.MastersGpa;
			model.MastersSubjects = individual.MastersSubjects;
			model.MastersInstitution = individual.MastersInstitution;
			model.MsGpa = individual.MsGpa;
			model.MsSubjects = individual.MsSubjects;
			model.MsInstitution = individual.MsInstitution;
			model.PhdSubjects = individual.PhdSubjects;
			model.PhdInstitution = individual.PhdInstitution;
			model.OtherQualification = individual.OtherQualification;

			model.CurrentJob = individual.CurrentJob;
			model.CompanyName = individual.CompanyName;
			model.Designation = individual.Designation;
			model.TotalJobExperience = individual.TotalJobExperience;

			model.BusinessName = individual.BusinessName;
			model.BusinessArea = individual.BusinessArea;
			model.BusinessNature = individual.BusinessNature;

			model.AppliedBefore = individual.AppliedBefore;
			model.AnyReligiousEducation = individual.AnyReligiousEducation;
			model.ReligiousEducationSpecify = individual.ReligiousEducationSpecify;
			model.AnyOtherExpertise = individual.AnyOtherExpertise;
			model.CurrentStatus = individual.CurrentStatus;
			model.Education = individual.Education;

			model.PaymentMethod = individual.PaymentMethod;
            model.RegistrationStatus = individual.RegistrationStatus;
            model.Phone = individual.Phone;

            // new fields for sisters
            model.FatherOrHusbandName = individual.FatherOrHusbandName;
            model.ClassSelection = individual.ClassSelection;
            model.WhatsAppNumber = individual.WhatsAppNumber;
            model.EducationDetails = individual.EducationDetails;
            model.Responsibilities = individual.Responsibilities;
            model.ProfessionStudyBusinessDetails = individual.ProfessionStudyBusinessDetails;
            model.CityDetails = individual.CityDetails;
        }

        #endregion
    }
}

Connect/Views/Signup/RegisterSisters.cshtml
@using Connect.Classes.DataModels
@using Connect.Classes.Helpers
@using Connect.Classes

@model Connect.Models.SignupViewModel
@{
    ViewBag.Title = "Al Burhan Institute Signup";
}

<div>
    <div>
        <h5>Your e-mail address (login user name) is <span style="color:#32597c;">@Model.Email</span></h5>
    </div>
    <div class="container" style="font-family:Helvetica, Arial, sans-serif; line-height:1.5; -webkit-font-smoothing: antialiased; color:#004242;">
        <div class="row">
            <div>
                @using (Html.BeginForm("Register", "Signup", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.Id)

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger col-md-2" })
                    <div>
                        <div style="float:right;">
                            @Html.ActionLink("Back to Details", "PreviewForAdmin", "Main", new { id = Model.Id }, null)
                        </div>
                        <br/>
                        <table id="details_plain_small">
                            <tr><td colspan="3"><hr /></td></tr>
                            <tr>
                                <td colspan="3">
                                    <p class="section-heading2"><img width="35" height="30" src="~/Images/contact-details.png"><span style="padding-left: 15px;">Contact Details</span></p>
                                </td>
                            </tr>

                            @if (SessionHelper.LoggedInUser.UserType != UserType.Applicant && Model.RegistrationStatus != RegistrationStatus.Enrolled)
                            {
                                <tr class="form-group">
                                    <td>@Html.LabelFor(model => model.Name, "Name")</td>
                                    <td>
                                        <div>
                                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "textbox-my", MaxLength = "50", MinLength = "1", placeholder = "Name" } })
                                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                        </div>
                                    </td>
                                </tr>

                                <tr class="form-group">
                                    <td>@Html.LabelFor(model => model.NicNumber, "CNIC Number")</td>
                                    <td>
                                        <div>
                                            @Html.EditorFor(model => model.NicNumber, new { htmlAttributes = new { @class = "textbox-my JS_MaxNicNumber", MaxLength = "13", placeholder = "13 digit Cnic Number" } })
                                            @Html.ValidationMessageFor(model => model.NicNumber, "", new { @class = "text-danger" })
                                        </div>
                                    </td>
                                </tr>
                            }

                            <tr class="form-group">
                                <td>@Html.LabelFor(model => model.FatherOrHusbandName, "Father/Husband Name")</td>
                                <td>
                                    <div>
                                        @Html.EditorFor(model => model.FatherOrHusbandName, new { htmlAttributes = new { @class = "textbox-my", MaxLength = "50", MinLength = "1", placeholder = "Father/Husband Name" } })
                                        @Html.ValidationMessageFor(model => model.FatherOrHusbandName, "", new { @class = "text-danger" })
                                    </div>
                                </td>
                            </tr>

                            <tr class="form-group">
                                <td>@Html.LabelFor(model => model.Phone, "Contact Number")</td>
                                <td>
                                    <div>
                                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "textbox-my JS_MaxOtherContact", placeholder = "Phone: 03xxxxxxxxx", MaxLength = "14", MinLength = "5" } })
                                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                                    </div>
                                </td>
                            </tr>

                            <tr class="form-group">
                                <td>@Html.LabelFor(model => model.WhatsAppNumber, "WhatsApp Number")</td>
                                <td>
                                    <div>
                                        @Html.EditorFor(model => model.WhatsAppNumber, new { htmlAttributes = new { @class = "textbox-my JS_MaxOtherContact", placeholder = "Phone: 03xxxxxxxxx", MaxLength = "14", MinLength = "5" } })
                                        @Html.ValidationMessageFor(model => model.WhatsAppNumber, "", new { @class = "text-danger" })
                                    </div>
                                </td>
                            </tr>

                            <tr class="form-group">
                                <td>@Html.LabelFor(model => model.OtherContact, "Other Contact Number")</td>
                                <td>
                                    <div>
                                        @Html.EditorFor(model => model.OtherContact, new { htmlAttributes = new { @class = "textbox-my JS_MaxOtherContact", placeholder = "Phone: 03xxxxxxxxx", MaxLength = "14", MinLength = "5" } })
                                        @Html.ValidationMessageFor(model => model.OtherContact, "", new { @class = "text-danger" })
                                    </div>
                                </td>
                            </tr>
                            <tr class="form-group">
                                <td>@Html.LabelFor(model => model.ResidentialAddress, "Residential Address")</td>
                                <td>
                                    <div>
                                        @Html.EditorFor(model => model.ResidentialAddress, new { htmlAttributes = new { @class = "textbox-my", placeholder = "Residential Address", MaxLength = "128" } })
                                        @Html.ValidationMessageFor(model => model.ResidentialAddress, "", new { @class = "text-danger" })
                                    </div>
                                </td>
                            </tr>
                            <tr class="form-group">
                                <td>@Html.LabelFor(model => model.MaritalStatus, "Marital Status")</td>
                                <td>
                                    <div>
                                        @Html.EnumDropDownListFor(model => model.MaritalStatus, new { @class = "form-dropdown-my", placeholder = "Marital Status" })
                                    </div>
                                </td>
                            </tr>

                        </table>
                    </div>
                    <br />
                    <div>
                        <p class="JS_Education_Message" style="display: none;">@Html.Label("please provide values for each of the education fields below", new { @class = "text-danger" })</p>
                        <table id="details_plain_small">
                            <tr><td colspan="2"><hr /></td></tr>
                            <tr>
                                <td colspan="2">
                                    <p class="section-heading2"><img width="35" height="30" src="~/Images/education.png"><span style="padding-left: 15px;">Educational Background</span></p>
                                </td>
                            </tr>
                            <tr>
                                <td>@Html.Label("Education")</td>
                                <td>
                                    @Html.EditorFor(model => model.EducationDetails, new { htmlAttributes = new { @class = "textbox-my ", placeholder = "Education" } })
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.LabelFor(model => model.AnyReligiousEducation, "Any religious education?")
                                </td>

                                <td>
                                    <p>
                                        @Html.CheckBoxFor(model => model.AnyReligiousEducation, new { @class = "largerCheckbox" })
                                    </p>

                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.Label("Specify if Yes")
                                </td>
                                <td>
                                    @Html.EditorFor(model => model.ReligiousEducationSpecify, new { htmlAttributes = new { @class = "textbox-my", MaxLength = "128", placeholder = "Religious Education" } })
                                </td>
                            </tr>

                        </table>
                    </div>
                    <div>
                        <table id="details_plain_small">
                            <tr><td colspan="3"><hr /></td></tr>
                            <tr>
                                <td colspan="3">
                                    <p class="section-heading2">Profession / Studies / Business Details</p>
                                </td>
                            </tr>
                            <tr>
                                <td>@Html.Label("Profession, Study, Business Details?")</td>
                                <td>
                                    @Html.EditorFor(model => model.ProfessionStudyBusinessDetails, new { htmlAttributes = new { @class = "textbox-my", MaxLength = "128", placeholder = "Profession/Study/BusinessDetails" } })
                                </td>
                            </tr>
                        </table>
                    </div>

                    @if (SessionHelper.LoggedInUser.UserType == UserType.PaymentAdministrator || SessionHelper.LoggedInUser.UserType == UserType.Ceo)
                    {
                        <div class="JS_InterviewSelectionShowHide">
                            <table id="details_plain_small">
                                <tr><td colspan="3"><hr /></td></tr>
                                <tr>
                                    <td colspan="2">
                                        <p class="section-heading2">Interview Details</p>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <p>Change your interview date and time from the available slots</p>
                                    </td>
                                    <td>
                                        <p>@Html.ValidationMessage("InterviewSlotOccupied", new { @class = "text-danger" })</p>
                                        @Html.DropDownListFor(x => x.SelectedInterviewSlotId, new SelectList(Model.AvailableInterviewSlots, "InterviewSlotId", "Slot"), new { @class = "form-dropdown-my" })
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <br />
                    }
                    <br />
                    <div class="form-group">
                        <input type="submit" value="Save Details" class="btn btn-default submit_register button-my-apply" />
                    </div>

                </div>
                }

            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}