Connect/Models/Admissions/Admission.cs
using Connect.Classes;
using System;
using System.Collections.Generic;

namespace Connect.Models.Admissions
{
    public class AdmissionViewModel
    {
        public IEnumerable<Admission> Admissions { get; set; }
    }

    public class Admission
    {
        public string RollNumberFormat { get; set; }
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string IndividualId { get; set; }
        public long Phone { get; set; }
        public int Age { get; set; }
        public RegistrationStatus RegistrationStatus { get; set; }
        public DateTime Created { get; set; }
        public string CeoComments { get; set; }
        public int CeoGrade;
        public int PanelGrade;
        public string CeoGradeValue => GetGradeValue(CeoGrade);
        public string PanelGradeValue => GetGradeValue(PanelGrade);
        public bool EmailSent { get; set; }
        public string Section { get; set; }
        public int RollNumber { get; set; }
        public string Timing { get; set; }

        private string GetGradeValue(int grade)
        {
            switch (grade)
            {
                case 1:
                    return "C";
                case 2:
                    return "B";
                case 3:
                    return "B+";
                case 4:
                    return "A-";
                case 5:
                    return "A";
                case 6:
                    return "A+";
                case 7:
                    return "Listener";
                case 8:
                    return "Not Graded";
                default:
                    return "";
            }
        }
    }
}

Connect/Controllers/AdmissionsController.cs
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading;
using System.Web.Mvc;
using Connect.Classes;
using Connect.Classes.Dapper;
using Connect.Classes.DataModels;
using Connect.Classes.Helpers;
using Connect.Classes.Security;
using Connect.Models.Admissions;

namespace Connect.Controllers
{
    [AuthorizeRole(UserType.Ceo, UserType.Manager)]
    public class AdmissionsController : Controller
    {
        // GET: Interview
        [HttpGet]
        [Route("GetCandidatesForCeoDecision")]          // candidates that had their CEO interview done
        public ActionResult GetCandidatesForCeoDecision()
        {

            IEnumerable<Admission> interviewes = new List<Admission>();
            // get all payments that are due verification
            if (SessionHelper.LoggedInUser.Batch.Contains("-BW"))
            {
                interviewes = new IndividualRepository().GetCeoInterviewedFemaleCandidatesForFinalDecision();
            }
            else
            {
                interviewes = new IndividualRepository().GetCeoInterviewedCandidatesForFinalDecision();
            }

            var pvm = new AdmissionViewModel();
            pvm.Admissions = interviewes;
            return View("admission", pvm);
        }

        [HttpGet]
        [Route("GetOrderedEnrolledCandidates")]          // candidates that had their CEO interview done
        public PartialViewResult GetOrderedEnrolledCandidates(string orderBy = "age")
        {
            IEnumerable<Admission> interviewes = null;
            interviewes = new IndividualRepository().GetCeoInterviewedCandidatesForFinalDecision().Where(c => c.RegistrationStatus == RegistrationStatus.Enrolled);

            var pvm = new AdmissionViewModel();
            pvm.Admissions = interviewes;

            PartialViewResult pv = null;
            pv = PartialView("~/Views/Admissions/Enrolled.cshtml", pvm);
            return pv;
        }

        [HttpPost]
        [Route("update-section")]
        public JsonResult UpdateSectionAjax(string ids, string section)
        {
            var repository = new IndividualRepository();

            if (ids != null)
            {
                var idArray = ids.Split(',');
                for (int i = 0; i < idArray.Length; i++)
                {
                    // Update the Section on the Individual
                    repository.UpdateIndividualSection(int.Parse(idArray[i]), section);
                }
            }

            var interviewes = repository.GetCeoInterviewedCandidatesForFinalDecision();
            var countEmailsnotSent = interviewes.Count(c => c.RegistrationStatus == RegistrationStatus.Enrolled && !c.EmailSent);
            var countSectionsNotAssigned = interviewes.Count(c => c.RegistrationStatus == RegistrationStatus.Enrolled && (string.IsNullOrEmpty(c.Section) || c.Section.ToLower() == "none" || c.Section.ToLower() == "notselected"));

            return Json(new { ok = true, emails = countEmailsnotSent, sections = countSectionsNotAssigned });
        }

        [HttpPost]
        [Route("send-email")]
        public JsonResult SendEmailAjax(string ids)
        {
            var repository = new IndividualRepository();

            if (ids != null)
            {
                var idArray = ids.Split(',');
                for (int i = 0; i < idArray.Length; i++)
                {
                    var csvEmailAndSectionAndRollNumber = repository.UpdateIndividualEnrolmentEmailSentStatus(int.Parse(idArray[i]));
                    if(!string.IsNullOrEmpty(csvEmailAndSectionAndRollNumber) && csvEmailAndSectionAndRollNumber.Contains(","))
                        SendEmail(csvEmailAndSectionAndRollNumber.Split(',')[0], $"{csvEmailAndSectionAndRollNumber.Split(',')[1]}"
                            , $"{SessionHelper.LoggedInUser.Batch}-{csvEmailAndSectionAndRollNumber.Split(',')[2]}"
                            , SessionHelper.LoggedInUser.Batch);
                }
            }

            var interviewes = repository.GetCeoInterviewedCandidatesForFinalDecision();
            var countEmailsnotSent = interviewes.Count(c => c.RegistrationStatus == RegistrationStatus.Enrolled && !c.EmailSent);
            var countSectionsNotAssigned = interviewes.Count(c => c.RegistrationStatus == RegistrationStatus.Enrolled && (string.IsNullOrEmpty(c.Section) || c.Section.ToLower() == "none" || c.Section.ToLower() == "notselected"));

            return Json(new { ok = true, emails = countEmailsnotSent, sections = countSectionsNotAssigned });
        }

        [HttpPost]
        [Route("decision-partial")]
        public JsonResult PaymentsPartial(string ids, string decision)
        {
            var regStatus = RegistrationStatus.CeoInterviewed;
            switch (decision)
            {
                case "enrolled":
                    regStatus = RegistrationStatus.Enrolled;
                    break;
                case "rejected":
                    regStatus = RegistrationStatus.Rejected;
                    break;
                case "dropped":
                    regStatus = RegistrationStatus.Dropped;
                    break;
                default:
                    regStatus = RegistrationStatus.CeoInterviewed;
                    break;
            }

            var repository = new IndividualRepository();

            if(ids != null)
            {
                var idArray = ids.Split(',');
                for (int i = 0; i < idArray.Length; i++)
                {
                    var email = repository.UpdateIndividualStatus(int.Parse(idArray[i]), regStatus);

                    if (regStatus != RegistrationStatus.CeoInterviewed && regStatus != RegistrationStatus.Dropped)
                        SendEmail(email, regStatus == RegistrationStatus.Enrolled ? true : false, SessionHelper.LoggedInUser.Batch);
                }
            }

            return Json(new { ok = true });
        }

        private static void SendEmail(string email, string section, string rollNumber, string batch)
        {
            var subjectPending = "Important Information about your course";
            var siteAddress = ConfigurationManager.AppSettings["SiteAddress"];

            string bodyPending = $"Dear Alburhanian, \n\nRoll Number : {rollNumber}\n\nSection : {section}\n\n" +
                $"Attendance is mandatory. Please get yourself ready for one year " +
                $"Ilm-Deen course. \n\nIf your circumstances change or need any further details, feel free to contact Alburhan Team (0302 410 3622).";

            if (batch.ToLower() == "dec2019lhr")
            {
                bodyPending = $"Dear Alburhanian, \n\nRoll Number : {rollNumber}\n\nSection : {section}\n\n" +
                    $"Classes will commence on the 21st of December 2019. Attendance is mandatory. Please get yourself ready for one year " +
                    $"Ilm-Deen course. \n\nIf your circumstances change or need any further details, feel free to contact Alburhan Team (0302 410 3622).";
            }
            else if (batch.ToLower() == "dec2019isb")
            {
                bodyPending = $"Dear Alburhanian, \n\nRoll Number : {rollNumber}\n\nSection : {section}\n\n" +
                    $"Classes will commence on the 28th of December 2019. Attendance is mandatory. Please get yourself ready for one year " +
                    $"Ilm-Deen course. \n\nIf your circumstances change or need any further details, feel free to contact Alburhan Team (0302 410 3622).";
            }
            else if (batch.ToLower() == "dec2019khi")
            {
                bodyPending = $"Dear Alburhanian, \n\nRoll Number : {rollNumber}\n\nSection : {section}\n\n" +
                    $"Classes will commence on the 5th of January 2020. Attendance is mandatory. Please get yourself ready for one year " +
                    $"Ilm-Deen course. \n\nIf your circumstances change or need any further details, feel free to contact Alburhan Team (0302 410 3622).";
            }
            else if (batch.ToLower() == "dec2019isbw")
            {
                bodyPending = $"Dear Alburhanian, \n\nRoll Number : {rollNumber}\n\nSection : {section}\n\n" +
                    $"Classes will commence on the 28th of December 2019. Attendance is mandatory. Please get yourself ready for one year " +
                    $"Ilm-Deen course. \n\nIf your circumstances change or need any further details, feel free to contact Alburhan Team (0302 410 3622).";
            }

            new Thread(delegate () {
                EmailHelper.SendEmail(email, subjectPending, bodyPending, string.IsNullOrEmpty(ConfigurationManager.AppSettings["DecisionEmailCC"]) ? "" : ConfigurationManager.AppSettings["DecisionEmailCC"]);
            }).Start();
        }

        private static void SendEmail(string email, bool enrolled, string batch)
        {
            var subjectPending = "Al-Burhan Final decision on your application";
            //var isWomenBatch = batch.Contains("-BW");
            //if (isWomenBatch)
            //{
            //    subjectPending = "Application for Al-Burhan Women Course";
            //}

            var siteAddress = ConfigurationManager.AppSettings["SiteAddress"];

            string bodyPending;
            if (enrolled)
            {
                //if(isWomenBatch)
                //{
                //    bodyPending =
                //        $"Congratulations! We are pleased to announce that your application for Al-Burhan Women Course has been successful. \nPlease contact AlBurhan Team (0333 555 1120) for further coordination.";
                //}
                //else
                //{
                    bodyPending =
                        $"Congratulations! We are pleased to announce that your application has been successful. \nPlease contact AlBurhan Team (0302 410 3622) for further coordination.";

Connect/Views/Admissions/Admission.cshtml
﻿@model Connect.Models.Admissions.AdmissionViewModel
@using Connect.Classes.Helpers
@using System.Configuration;
@using Connect.Classes
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var rollNumberFormat = SessionHelper.LoggedInUser.Batch + "-";
    var sectionCapacity = int.Parse(ConfigurationManager.AppSettings["SectionCapacity"]);
    var loggedInUserType = SessionHelper.LoggedInUser.UserType;
}

<div style="background-color:rgba(195,195,195,.3); padding: 1px; border:beige 1px solid; border-radius:3px;">
    <div style="padding:2px;">
        <img style="float:left; padding: 5px;" src="~/Images/burhan2.png" width="85" height="85" />
        Batch <h4>@SessionHelper.LoggedInUser.Batch</h4>
        <h4 style="float:right;padding-right:2px; color:#413d62;">Admissions</h4>
    </div>
    <div style="clear:both;" />
    <hr style="height:2px; background-color:gray;" />

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="tab">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist" data-options="deep_linking: true">
                        <li role="presentation" class="active"><a href="#Section2" aria-controls="profile" role="tab" data-toggle="tab">Selected (@Model.Admissions.Count(c => c.RegistrationStatus == RegistrationStatus.Enrolled))</a></li>
                        <li role="presentation"><a href="#Section1" aria-controls="home" role="tab" data-toggle="tab">Pending Decision (@Model.Admissions.Count(c => c.CeoGrade > 0 && c.RegistrationStatus != RegistrationStatus.Enrolled && c.RegistrationStatus != RegistrationStatus.Rejected && c.RegistrationStatus != RegistrationStatus.Dropped))</a></li>
                        <li role="presentation"><a href="#Section3" aria-controls="profile" role="tab" data-toggle="tab">Rejected (@Model.Admissions.Count(c => c.RegistrationStatus == RegistrationStatus.Rejected))</a></li>
                        <li role="presentation"><a href="#Section4" aria-controls="profile" role="tab" data-toggle="tab">Dropped (@Model.Admissions.Count(c => c.RegistrationStatus == RegistrationStatus.Dropped))</a></li>
                    </ul>
                </div>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="Section2">
                        <div>
                            @{ Html.RenderAction("GetOrderedEnrolledCandidates", "Admissions", new { orderBy = "name" }); }
                        </div>

                    </div>
                    <div class="tab-pane fade" id="Section1">
                        <div style="font-size:smaller;" align="center">
                            @if (loggedInUserType == Connect.Classes.DataModels.UserType.Ceo)
                            {
                                <div>
                                    <table style="float:right;">
                                        <tr>
                                            <td>
                                                <button type="button" class="button-checkbox-selection" style="width:64px; border:none; float:right; padding:5px; background-color: darkgreen;border-radius: 4px; color: greenyellow; font-weight: bold;">Accept</button>
                                            </td>
                                            <td>
                                                <button type="button" class="button-checkbox-rejection" style="width:64px; border:none; float:right; padding:5px; background-color: red;border-radius: 4px; color: yellow; font-weight: bold;">Reject</button>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            }

                            <table id="details">
                                <tr>
                                    <th>
                                        <input type="checkbox" id="check_all_pending">
                                    </th>
                                    <th>
                                        <b>Name</b>
                                    </th>
                                    <th><b>Phone</b></th>
                                    <th>Age</th>
                                    <th>Username</th>
                                    @if (SessionHelper.LoggedInUser.UserType == Connect.Classes.DataModels.UserType.Ceo)
                                    {
                                        <th>Ceo Grade</th>
                                    }
                                </tr>

                                @foreach (var item in Model.Admissions.Where(c => c.CeoGrade > 0 && c.RegistrationStatus != RegistrationStatus.Enrolled && c.RegistrationStatus != RegistrationStatus.Rejected && c.RegistrationStatus != RegistrationStatus.Dropped))
                                {
                                    <tr>
                                        <td>
                                            <input type="checkbox" value=@item.IndividualId name="pending">
                                        </td>
                                        <td>
                                            @Html.ActionLink(item.Name, "PreviewForAdmin", "Main", new { id = item.Id }, null)
                                        </td>
                                        <td>
                                            <span>0</span>@item.Phone
                                        </td>
                                        <td>@item.Age</td>
                                        <td>
                                            @item.Email
                                        </td>
                                        @if (SessionHelper.LoggedInUser.UserType == Connect.Classes.DataModels.UserType.Ceo)
                                        {
                                            <td>
                                                @item.CeoGradeValue
                                            </td>
                                        }
                                    </tr>
                                }
                            </table>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="Section3">
                        <div style="font-size:smaller; overflow: auto;" align="center">

                            @if (loggedInUserType == Connect.Classes.DataModels.UserType.Ceo)
                            {
                                <div>
                                    <table style="float:right;">
                                        <tr>
                                            <td>
                                                <button type="button" class="button-checkbox-undo" style="width:100px; border:none; float:right; padding:5px; background-color: #32597c;border-radius: 4px; color: lightblue; font-weight: bold;">Undo Reject</button>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            }

                            <table id="details">
                                <tr>
                                    <th>
                                        <input type="checkbox" id="check_all_rejected">
                                    </th>
                                    <th>
                                        <b>Name</b>
                                    </th>
                                    <th><b>Phone</b></th>
                                    <th>Age</th>
                                    <th>Username</th>
                                    @if (SessionHelper.LoggedInUser.UserType == Connect.Classes.DataModels.UserType.Ceo)
                                    {
                                        <th>Ceo Grade</th>
                                    }
                                </tr>

                                @foreach (var item in Model.Admissions.Where(c => c.RegistrationStatus == RegistrationStatus.Rejected))
                                {
                                    <tr>
                                        <td><input type="checkbox" value=@item.IndividualId name="rejected"></td>
                                        <td>
                                            @Html.ActionLink(item.Name, "PreviewForAdmin", "Main", new { id = item.Id }, null)
                                        </td>
                                        <td>
                                            <span>0</span>@item.Phone
                                        </td>
                                        <td>@item.Age</td>
                                        <td>
                                            @item.Email
                                        </td>
                                        @if (SessionHelper.LoggedInUser.UserType == Connect.Classes.DataModels.UserType.Ceo)
                                        {
                                            <td>
                                                @item.CeoGradeValue
                                            </td>
                                        }

                                    </tr>
                                }

                            </table>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="Section4">
                        <div style="font-size:smaller; overflow: auto;" align="center">

                            @if (loggedInUserType == Connect.Classes.DataModels.UserType.Ceo)
                            {
                                <div>
                                    <table style="float:right;">
                                        <tr>
                                            <td>
                                                <button type="button" class="button-checkbox-undodrop" style="width:100px; border:none; float:right; padding:5px; background-color: #32597c;border-radius: 4px; color: lightblue; font-weight: bold;">UnDrop</button>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            }

                            <table id="details">
                                <tr>
                                    <th>
                                        <input type="checkbox" id="check_all_dropped">
                                    </th>
                                    <th>
                                        <b>Name</b>
                                    </th>
                                    <th><b>Phone</b></th>
                                    <th>Age</th>
                                    <th>Username</th>
                                    @if (SessionHelper.LoggedInUser.UserType == Connect.Classes.DataModels.UserType.Ceo)
                                    {
                                        <th>Ceo Grade</th>
                                        <th>Panel Grade</th>
                                    }
                                    <th>Section</th>
                                </tr>

                                @foreach (var item in Model.Admissions.Where(c => c.RegistrationStatus == RegistrationStatus.Dropped))
                                {
                                    <tr>
                                        <td><input type="checkbox" value=@item.IndividualId name="dropped"></td>
                                        <td>
                                            @Html.ActionLink(item.Name, "PreviewForAdmin", "Main", new { id = item.Id }, null)
                                        </td>
                                        <td>
                                            <span>0</span>@item.Phone
                                        </td>
                                        <td>@item.Age</td>
                                        <td>
                                            @item.Email
                                        </td>
                                        @if (SessionHelper.LoggedInUser.UserType == Connect.Classes.DataModels.UserType.Ceo)
                                        {
                                            <td>
                                                @item.CeoGradeValue
                                            </td>
                                            <td>
                                                @item.PanelGradeValue
                                            </td>
                                        }
                                        <td>
                                            @item.Section
                                        </td>
                                    </tr>
                                }

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}